default: &default
  adapter: mysql2
  encoding: utf8
  username: root

development:
  <<: *default
  database: doctor_app_development

test:
  <<: *default
  database: doctor_app_test

production:
  <<: *default
  database: doctor_app_production
  username: doctor_app
  password: <%= ENV['DEMISTIFIER_APP_DATABASE_PASSWORD'] %>
